package com.sivalabs.jcart.admin.web.models;
// Generated 2 Sep, 2018 1:04:52 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * CreditDetails generated by hbm2java
 */
@Entity
@DynamicInsert
@Table(name = "credit_details")
public class CreditDetails implements java.io.Serializable {

	private int crTransactionId;
	private float crTransactionAmount;
	private String crTransactionMoneyGiver;
	private String crTransactionMoneyTaker;
	private String crTransactionPaymentMode;
	private String crTransactionDescription;
	private Date crTransactionCreatedAt;
	private Date crTransactionModifiedAt;
	private Integer crTransactionAccountId;
	private Integer crTransactionUserId;
	private Integer crTransacionSourceId;
	private String crTransactionSourceName;
	private int crTransactionPassed;
	
	
	
	@Column(name = "cr_transaction_passed")
	public int getCrTransactionPassed() {
		return crTransactionPassed;
	}

	public void setCrTransactionPassed(int crTransactionPassed) {
		this.crTransactionPassed = crTransactionPassed;
	}

	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date crTransactionDate;
	
	
	public CreditDetails() {
	}

	public CreditDetails(int crTransactionId) {
		this.crTransactionId = crTransactionId;
	}

	public CreditDetails(int crTransactionId, Integer crTransactionAmount, String crTransactionMoneyGiver,
			String crTransactionMoneyTaker, String crTransactionPaymentMode, String crTransactionDescription,
			Date crTransactionCreatedAt, Date crTransactionModifiedAt, Integer crTransactionAccountId,
			Integer crTransactionUserId, Integer crTransacionSourceId, Date crTransactionDate) {
		this.crTransactionId = crTransactionId;
		this.crTransactionAmount = crTransactionAmount;
		this.crTransactionMoneyGiver = crTransactionMoneyGiver;
		this.crTransactionMoneyTaker = crTransactionMoneyTaker;
		this.crTransactionPaymentMode = crTransactionPaymentMode;
		this.crTransactionDescription = crTransactionDescription;
		this.crTransactionCreatedAt = crTransactionCreatedAt;
		this.crTransactionModifiedAt = crTransactionModifiedAt;
		this.crTransactionAccountId = crTransactionAccountId;
		this.crTransactionUserId = crTransactionUserId;
		this.crTransacionSourceId = crTransacionSourceId;
		this.crTransactionDate = crTransactionDate;
	}

	@Id

	@Column(name = "cr_transaction_id", unique = true, nullable = false)
	public int getCrTransactionId() {
		return this.crTransactionId;
	}

	public void setCrTransactionId(int crTransactionId) {
		this.crTransactionId = crTransactionId;
	}
	
	
	
	
	@Column(name = "cr_transaction_source_name")
	public String getCrTransactionSourceName() {
		return crTransactionSourceName;
	}

	public void setCrTransactionSourceName(String crTransactionSourceName) {
		this.crTransactionSourceName = crTransactionSourceName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cr_transaction_date")
	public Date getCrTransactionDate() {
		return crTransactionDate;
	}

	public void setCrTransactionDate(Date crTransactionDate) {
		this.crTransactionDate = crTransactionDate;
	}

	@Column(name = "cr_transaction_amount")
	public float getCrTransactionAmount() {
		return this.crTransactionAmount;
	}

	public void setCrTransactionAmount(float crTransactionAmount) {
		this.crTransactionAmount = crTransactionAmount;
	}

	@Column(name = "cr_transaction_money_giver")
	public String getCrTransactionMoneyGiver() {
		return this.crTransactionMoneyGiver;
	}

	public void setCrTransactionMoneyGiver(String crTransactionMoneyGiver) {
		this.crTransactionMoneyGiver = crTransactionMoneyGiver;
	}

	@Column(name = "cr_transaction_money_taker")
	public String getCrTransactionMoneyTaker() {
		return this.crTransactionMoneyTaker;
	}

	public void setCrTransactionMoneyTaker(String crTransactionMoneyTaker) {
		this.crTransactionMoneyTaker = crTransactionMoneyTaker;
	}

	@Column(name = "cr_transaction_payment_mode")
	public String getCrTransactionPaymentMode() {
		return this.crTransactionPaymentMode;
	}

	public void setCrTransactionPaymentMode(String crTransactionPaymentMode) {
		this.crTransactionPaymentMode = crTransactionPaymentMode;
	}

	@Column(name = "cr_transaction_description")
	public String getCrTransactionDescription() {
		return this.crTransactionDescription;
	}

	public void setCrTransactionDescription(String crTransactionDescription) {
		this.crTransactionDescription = crTransactionDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_transaction_created_at", length = 19)
	public Date getCrTransactionCreatedAt() {
		return this.crTransactionCreatedAt;
	}

	public void setCrTransactionCreatedAt(Date crTransactionCreatedAt) {
		this.crTransactionCreatedAt = crTransactionCreatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_transaction_modified_at", length = 19)
	public Date getCrTransactionModifiedAt() {
		return this.crTransactionModifiedAt;
	}

	public void setCrTransactionModifiedAt(Date crTransactionModifiedAt) {
		this.crTransactionModifiedAt = crTransactionModifiedAt;
	}

	@Column(name = "cr_transaction_account_id")
	public Integer getCrTransactionAccountId() {
		return this.crTransactionAccountId;
	}

	public void setCrTransactionAccountId(Integer crTransactionAccountId) {
		this.crTransactionAccountId = crTransactionAccountId;
	}

	@Column(name = "cr_transaction_user_id")
	public Integer getCrTransactionUserId() {
		return this.crTransactionUserId;
	}

	public void setCrTransactionUserId(Integer crTransactionUserId) {
		this.crTransactionUserId = crTransactionUserId;
	}

	@Column(name = "cr_transacion_source_id")
	public Integer getCrTransacionSourceId() {
		return this.crTransacionSourceId;
	}

	public void setCrTransacionSourceId(Integer crTransacionSourceId) {
		this.crTransacionSourceId = crTransacionSourceId;
	}

	@Override
	public String toString() {
		return "CreditDetails [crTransactionId=" + crTransactionId + ", crTransactionAmount=" + crTransactionAmount
				+ ", crTransactionMoneyGiver=" + crTransactionMoneyGiver + ", crTransactionMoneyTaker="
				+ crTransactionMoneyTaker + ", crTransactionPaymentMode=" + crTransactionPaymentMode
				+ ", crTransactionDescription=" + crTransactionDescription + ", crTransactionCreatedAt="
				+ crTransactionCreatedAt + ", crTransactionModifiedAt=" + crTransactionModifiedAt
				+ ", crTransactionAccountId=" + crTransactionAccountId + ", crTransactionUserId=" + crTransactionUserId
				+ ", crTransacionSourceId=" + crTransacionSourceId + "]";
	}
}
