package com.sivalabs.jcart.admin.web.models;
// Generated 2 Sep, 2018 1:04:52 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * DebitDetails generated by hbm2java
 */
@Entity
@DynamicInsert
@Table(name = "debit_details")
public class DebitDetails implements java.io.Serializable {

	private int debTransactionId;
	private float debTransactionAmount;
	private String debTransactionMoneyGiver;
	private String debTransactionMoneyTaker;
	private String debTransactionPaymentMode;
	private String debTransactionDescription;
	private Date debTransactionCreatedAt;
	private Date debTransactionModifiedAt;
	private Integer debTransactionAccountId;
	private Integer debTransactionUserId;
	private Integer debTransactionSourceId;
	private String debTransactionSourceName;
	
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	private Date debTransactionDate;
	
	public DebitDetails() {
	}

	public DebitDetails(int debTransactionId) {
		this.debTransactionId = debTransactionId;
	}

	public DebitDetails(int debTransactionId, float debTransactionAmount, String debTransactionMoneyGiver,
			String debTransactionMoneyTaker, String debTransactionPaymentMode, String debTransactionDescription,
			Date debTransactionCreatedAt, Date debTransactionModifiedAt, Integer debTransactionAccountId,
			Integer debTransactionUserId, Integer debTransactionSourceId, Date debTransactionDate) {
		this.debTransactionId = debTransactionId;
		this.debTransactionAmount = debTransactionAmount;
		this.debTransactionMoneyGiver = debTransactionMoneyGiver;
		this.debTransactionMoneyTaker = debTransactionMoneyTaker;
		this.debTransactionPaymentMode = debTransactionPaymentMode;
		this.debTransactionDescription = debTransactionDescription;
		this.debTransactionCreatedAt = debTransactionCreatedAt;
		this.debTransactionModifiedAt = debTransactionModifiedAt;
		this.debTransactionAccountId = debTransactionAccountId;
		this.debTransactionUserId = debTransactionUserId;
		this.debTransactionSourceId = debTransactionSourceId;
		this.debTransactionDate = debTransactionDate;
	}

	@Id

	@Column(name = "deb_transaction_id", unique = true, nullable = false)
	public int getDebTransactionId() {
		return this.debTransactionId;
	}

	public void setDebTransactionId(int debTransactionId) {
		this.debTransactionId = debTransactionId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "deb_transaction_date")
	public Date getDebTransactionDate() {
		return debTransactionDate;
	}

	public void setDebTransactionDate(Date debTransactionDate) {
		this.debTransactionDate = debTransactionDate;
	}
	
	
	
	@Column(name = "deb_transaction_source_name")
	public String getDebTransactionSourceName() {
		return debTransactionSourceName;
	}

	public void setDebTransactionSourceName(String debTransactionSourceName) {
		this.debTransactionSourceName = debTransactionSourceName;
	}

	@Column(name = "deb_transaction_amount")
	public float getDebTransactionAmount() {
		return this.debTransactionAmount;
	}

	public void setDebTransactionAmount(float debTransactionAmount) {
		this.debTransactionAmount = debTransactionAmount;
	}

	@Column(name = "deb_transaction_money_giver")
	public String getDebTransactionMoneyGiver() {
		return this.debTransactionMoneyGiver;
	}

	public void setDebTransactionMoneyGiver(String debTransactionMoneyGiver) {
		this.debTransactionMoneyGiver = debTransactionMoneyGiver;
	}

	@Column(name = "deb_transaction_money_taker")
	public String getDebTransactionMoneyTaker() {
		return this.debTransactionMoneyTaker;
	}

	public void setDebTransactionMoneyTaker(String debTransactionMoneyTaker) {
		this.debTransactionMoneyTaker = debTransactionMoneyTaker;
	}

	@Column(name = "deb_transaction_payment_mode", length = 45)
	public String getDebTransactionPaymentMode() {
		return this.debTransactionPaymentMode;
	}

	public void setDebTransactionPaymentMode(String debTransactionPaymentMode) {
		this.debTransactionPaymentMode = debTransactionPaymentMode;
	}

	@Column(name = "deb_transaction_description")
	public String getDebTransactionDescription() {
		return this.debTransactionDescription;
	}

	public void setDebTransactionDescription(String debTransactionDescription) {
		this.debTransactionDescription = debTransactionDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deb_transaction_created_at", length = 19)
	public Date getDebTransactionCreatedAt() {
		return this.debTransactionCreatedAt;
	}

	public void setDebTransactionCreatedAt(Date debTransactionCreatedAt) {
		this.debTransactionCreatedAt = debTransactionCreatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deb_transaction_modified_at", length = 19)
	public Date getDebTransactionModifiedAt() {
		return this.debTransactionModifiedAt;
	}

	public void setDebTransactionModifiedAt(Date debTransactionModifiedAt) {
		this.debTransactionModifiedAt = debTransactionModifiedAt;
	}

	@Column(name = "deb_transaction_account_id")
	public Integer getDebTransactionAccountId() {
		return this.debTransactionAccountId;
	}

	public void setDebTransactionAccountId(Integer debTransactionAccountId) {
		this.debTransactionAccountId = debTransactionAccountId;
	}

	@Column(name = "deb_transaction_user_id")
	public Integer getDebTransactionUserId() {
		return this.debTransactionUserId;
	}

	public void setDebTransactionUserId(Integer debTransactionUserId) {
		this.debTransactionUserId = debTransactionUserId;
	}

	@Column(name = "deb_transaction_source_id")
	public Integer getDebTransactionSourceId() {
		return this.debTransactionSourceId;
	}

	public void setDebTransactionSourceId(Integer debTransactionSourceId) {
		this.debTransactionSourceId = debTransactionSourceId;
	}

	@Override
	public String toString() {
		return "DebitDetails [debTransactionId=" + debTransactionId + ", debTransactionAmount=" + debTransactionAmount
				+ ", debTransactionMoneyGiver=" + debTransactionMoneyGiver + ", debTransactionMoneyTaker="
				+ debTransactionMoneyTaker + ", debTransactionPaymentMode=" + debTransactionPaymentMode
				+ ", debTransactionDescription=" + debTransactionDescription + ", debTransactionCreatedAt="
				+ debTransactionCreatedAt + ", debTransactionModifiedAt=" + debTransactionModifiedAt
				+ ", debTransactionAccountId=" + debTransactionAccountId + ", debTransactionUserId="
				+ debTransactionUserId + ", debTransactionSourceId=" + debTransactionSourceId
				+ ", debTransactionSourceName=" + debTransactionSourceName + ", debTransactionDate="
				+ debTransactionDate + "]";
	}

}
