package com.sivalabs.jcart.admin.web.models;
// Generated 2 Sep, 2018 1:04:52 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * UserDefinedSources generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "user_defined_client")
public class UserDefinedClients implements java.io.Serializable {

	private int udClientId;
	private int udClientType;
	private String udClientName;
	private String  udClientDescription;
	private Date udClientCreatedAt;
	private Date udClientUpdatedAt;
	private int udClientAccountId;
	private int udClientUserId;
	

	
	
	

	public UserDefinedClients() {
	}

	public UserDefinedClients(int udClientId) {
		this.udClientId = udClientId;
	}

	public UserDefinedClients(int udClientId, short udClientType, String udClientName, String udClientDescription,
			Date udClientCreatedAt, Date udClientUpdatedAt, int udClientAccountId, int udClientUserId) {
		this.udClientId = udClientId;
		this.udClientType = udClientType;
		this.udClientName = udClientName;
		this.udClientDescription = udClientDescription;
		this.udClientCreatedAt = udClientCreatedAt;
		this.udClientUpdatedAt = udClientUpdatedAt;
		this.udClientAccountId = udClientAccountId;
		this.udClientUserId = udClientUserId;
	}

	@Id

	@Column(name = "ud_client_id", unique = true, nullable = false)
	public int getUdClientId() {
		return udClientId;
	}

	public void setUdClientId(int udClientId) {
		this.udClientId = udClientId;
	}

	@Column(name = "ud_client_type")
	public int getUdClientType() {
		return udClientType;
	}

	public void setUdClientType(int udClientType) {
		this.udClientType = udClientType;
	}

	@Column(name = "ud_client_name")
	public String getUdClientName() {
		return udClientName;
	}

	public void setUdClientName(String udClientName) {
		this.udClientName = udClientName;
	}

	@Column(name = "ud_client_description")
	public String getUdClientDescription() {
		return udClientDescription;
	}

	public void setUdClientDescription(String udClientDescription) {
		this.udClientDescription = udClientDescription;
	}
	
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ud_client_created_at", length = 19)
	public Date getUdClientCreatedAt() {
		return udClientCreatedAt;
	}

	public void setUdClientCreatedAt(Date udClientCreatedAt) {
		this.udClientCreatedAt = udClientCreatedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ud_client_updated_at", length = 19)
	public Date getUdClientUpdatedAt() {
		return udClientUpdatedAt;
	}

	public void setUdClientUpdatedAt(Date udClientUpdatedAt) {
		this.udClientUpdatedAt = udClientUpdatedAt;
	}

	@Column(name = "ud_client_account_id")
	public int getUdClientAccountId() {
		return udClientAccountId;
	}

	public void setUdClientAccountId(int udClientAccountId) {
		this.udClientAccountId = udClientAccountId;
	}

	@Column(name = "ud_client_user_id")
	public int getUdClientUserId() {
		return udClientUserId;
	}

	public void setUdClientUserId(int udClientUserId) {
		this.udClientUserId = udClientUserId;
	}

}
