package com.sivalabs.jcart.admin.web.models;
// Generated 2 Sep, 2018 1:04:52 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * UserDefinedSources generated by hbm2java
 */
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "user_defined_sources")
public class UserDefinedSources implements java.io.Serializable {

	private int sourceId;
	private String sourceName;
	private Integer accountId;
	private Date createdAt;
	private Date modifiedAt;
	private String sourceDescription;
	private int userId;
	
	
	public UserDefinedSources() {
	}

	public UserDefinedSources(int sourceId) {
		this.sourceId = sourceId;
	}

	public UserDefinedSources(int sourceId, String sourceName, Integer accountId, Date createdAt, Date modifiedAt, String sourceDescription) {
		this.sourceId = sourceId;
		this.sourceName = sourceName;
		this.accountId = accountId;
		this.createdAt = createdAt;
		this.modifiedAt = modifiedAt;
		this.sourceDescription = sourceDescription;
	}

	@Id

	@Column(name = "source_id", unique = true, nullable = false)
	public int getSourceId() {
		return this.sourceId;
	}

	public void setSourceId(int sourceId) {
		this.sourceId = sourceId;
	}
	
	
	@Column(name = "source_description")
	public String getSourceDescription() {
		return sourceDescription;
	}

	public void setSourceDescription(String sourceDescription) {
		this.sourceDescription = sourceDescription;
	}

	@Column(name = "source_name")
	public String getSourceName() {
		return this.sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}

	@Column(name = "account_id")
	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	
	@Column(name = "user_id")
	public int getUserId() {
		return userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_at", length = 19)
	public Date getModifiedAt() {
		return this.modifiedAt;
	}

	public void setModifiedAt(Date modifiedAt) {
		this.modifiedAt = modifiedAt;
	}

}
